force-app/main/default/objects/Contact/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RankImageUrl__c.field-meta.xml
<CustomField>
    <fullName>RankImageUrl__c</fullName>
    <label>Rank Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TrailblazerId__c.field-meta.xml
<CustomField>
    <fullName>TrailblazerId__c</fullName>
    <label>Trailblazer Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrailblazerCertification__c/TrailblazerCertification__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Certification</label>
    <nameField>
        <label>Certification Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TrailblazerCertification__c/fields/CertificationImageUrl__c.field-meta.xml
<CustomField>
    <fullName>CertificationImageUrl__c</fullName>
    <label>Certification Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrailblazerCertification__c/fields/CertificationUrl__c.field-meta.xml
<CustomField>
    <fullName>CertificationUrl__c</fullName>
    <label>Certification Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/TrailblazerCertification__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trailblazer Certifications</relationshipLabel>
    <relationshipName>TrailblazerCertifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TrailblazerCertification__c/fields/ExpiredAt__c.field-meta.xml
<CustomField>
    <fullName>ExpiredAt__c</fullName>
    <label>Expired at</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrailblazerCertification__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field is a compound key with the following pattern: &lt;TrailblazerId&gt;/&lt;title&gt;/&lt;title&gt; generated during record creation by integration service.</description>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/TrailblazerProfileStatus__c.object-meta.xml
<CustomObject>
    <label>Trailblazer Profile Status</label>
    <nameField>
        <label>Trailblazer Counts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trailblazer Profile Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/BadgesForNextRank__c.field-meta.xml
<CustomField>
    <fullName>BadgesForNextRank__c</fullName>
    <label>Badges for Next Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trailblazer Profile Statuses</relationshipLabel>
    <relationshipName>TrailblazerProfileStatuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/PointsForNextRank__c.field-meta.xml
<CustomField>
    <fullName>PointsForNextRank__c</fullName>
    <label>Points for Next Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/RankImageUrl__c.field-meta.xml
<CustomField>
    <fullName>RankImageUrl__c</fullName>
    <label>Rank Image Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/StatusDate__c.field-meta.xml
<CustomField>
    <fullName>StatusDate__c</fullName>
    <label>Status Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/TotalCompletedTrails__c.field-meta.xml
<CustomField>
    <fullName>TotalCompletedTrails__c</fullName>
    <label>Total Completed Trails</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/TotalEarnedBadges__c.field-meta.xml
<CustomField>
    <fullName>TotalEarnedBadges__c</fullName>
    <label>Total Earned Badges</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrailblazerProfileStatus__c/fields/TotalEarnedPoints__c.field-meta.xml
<CustomField>
    <fullName>TotalEarnedPoints__c</fullName>
    <label>Total Earned Points</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TrailblazerProfileTrackerController.cls
public with sharing class TrailblazerProfileTrackerController {
    
    public static void updateContactWithProfileCounts(String profile, TrailblazerProfileCounts profileCounts) {
       
        Contact trailblazerContact = findRelatedContact(profile);

        createNewProfileStatusRecord(trailblazerContact,profileCounts);

    }

    public static Contact findRelatedContact(String profile) {
        List<Contact> relatedContacts = [SELECT Id,FirstName,TrailblazerId__c FROM Contact WHERE TrailblazerId__c =: profile];
        return relatedContacts != null ? relatedContacts[0] : null;
    } 

    public static String createNewProfileStatusRecord(Contact c, TrailblazerProfileCounts counts) {
        TrailblazerProfileStatus__c newProfileStatus = new TrailblazerProfileStatus__c();
        newProfileStatus.Name = c.FirstName + ' ('+c.TrailblazerId__c+') '+' - '+Date.Today();
        newProfileStatus.Contact__c = c.Id;
        newProfileStatus.StatusDate__c = Date.Today();
        newProfileStatus.Rank__c = counts.RankLabel;
        newProfileStatus.RankImageUrl__c = counts.RankImageUrl;
        newProfileStatus.TotalCompletedTrails__c = counts.CompletedTrailTotal;
        newProfileStatus.TotalEarnedBadges__c = counts.EarnedBadgeTotal;
        newProfileStatus.TotalEarnedPoints__c = counts.EarnedPointTotal;
        newProfileStatus.BadgesForNextRank__c = counts.BadgeTotalForNextRank;
        newProfileStatus.PointsForNextRank__c = counts.PointTotalForNextRank;
        insert(newProfileStatus);

        c.Rank__c = counts.RankLabel;
        c.RankImageUrl__c = counts.RankImageUrl;
        update(c);

        return 'New status '+ newProfileStatus.Name + 'created for '+c.TrailblazerId__c+'!!';
    }

    public static void updateContactWithCertifications(String profile, List<TrailblazerCertification> certificationList) {
        Contact trailblazerContact = findRelatedContact(profile);

        upsertCertificationListRecords(trailblazerContact, certificationList);
    }

    public static void upsertCertificationListRecords(Contact trailblazerContact, List<TrailblazerCertification> certifications) {

        List<TrailblazerCertification__c> certificationsToUpsert = new List<TrailblazerCertification__c>();

        for(TrailblazerCertification certification : certifications) {
            TrailblazerCertification__c newCert = new TrailblazerCertification__c();
            newCert.Name = certification.title;
            newCert.Key__c = trailblazerContact.TrailblazerId__c + '/' + certification.dateCompleted + '/' + certification.title;
            newCert.Description__c = certification.description;
            newCert.IssueDate__c = getDateFromString(certification.dateCompleted);
            newCert.ExpiredAt__c = getDateFromString(certification.dateExpired);
            newCert.CertificationUrl__c = certification.certificationUrl;
            newCert.Status__c = certification.certificationStatus;
            newCert.CertificationImageUrl__c = certification.certificationImageUrl;
            newCert.Contact__c = trailblazerContact.Id;
            certificationsToUpsert.add(newCert);
        }

        upsert certificationsToUpsert  Key__c;

    }

    public static Date getDateFromString(String sdate) {
        List<String> sDateSplited = sdate.split('-');
        if(sDateSplited.size() == 3) {
            Integer year    = Integer.valueOf(sDateSplited[0]);
            Integer month   = Integer.valueOf(sDateSplited[1]);
            Integer day     = Integer.valueOf(sDateSplited[2]);
            return Date.newInstance(year,month,day);
        } else {
            return null;
        } 
    }


}